<Project>
  <PropertyGroup>
    <Authors>Omi Developers</Authors>
    <Version>1.64</Version>
    <IsPackable Condition="'$(MSBuildProjectName)' != 'Iex.IexEquities.Tops.IexTp.v1.64'">false</IsPackable>
    <PackageId Condition="'$(MSBuildProjectName)' == 'Iex.IexEquities.Tops.IexTp.v1.64'">Iex.IexEquities.Tops.IexTp.v1.64.Classes</PackageId>
  </PropertyGroup>
</Project>
