<Project>
  <PropertyGroup>
    <Authors>Omi Developers</Authors>
    <Version>1.66</Version>
    <IsPackable Condition="'$(MSBuildProjectName)' != 'Iex.IexEquities.Tops.IexTp.v1.66'">false</IsPackable>
    <PackageId Condition="'$(MSBuildProjectName)' == 'Iex.IexEquities.Tops.IexTp.v1.66'">Iex.IexEquities.Tops.IexTp.v1.66.Classes</PackageId>
  </PropertyGroup>
</Project>
