<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
<TargetFramework>net10.0</TargetFramework>
<ImplicitUsings>enable</ImplicitUsings>
<Nullable>enable</Nullable>
</PropertyGroup>

<ItemGroup>
<ProjectReference Include="../../../../Pcap.CSharp/Pcap.CSharp.csproj" />
<ProjectReference Include="../Iex.IexEquities.Deep.IexTp.v1.08\Iex.IexEquities.Deep.IexTp.v1.08.csproj" />
</ItemGroup>

</Project>
