<Project>
  <PropertyGroup>
    <Authors>Omi Developers</Authors>
    <Version>1.04</Version>
    <IsPackable Condition="'$(MSBuildProjectName)' != 'Iex.IexEquities.DeepPlus.IexTp.v1.04'">false</IsPackable>
    <PackageId Condition="'$(MSBuildProjectName)' == 'Iex.IexEquities.DeepPlus.IexTp.v1.04'">Iex.IexEquities.DeepPlus.IexTp.v1.04.ZeroCopy</PackageId>
  </PropertyGroup>
</Project>
